In [1]:
a = [1.0, 2.0, 3.0]
a

[1.0, 2.0, 3.0]

In [2]:
import torch

In [3]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [4]:
a[1]

tensor(1.)

In [5]:
float(a[1])

1.0

In [6]:
a[2] = 3.0
a

tensor([1., 1., 3.])

In [7]:
points = torch.tensor([4.0,1,5,3,2,1])
points

tensor([4., 1., 5., 3., 2., 1.])

In [8]:
float(points[0])

4.0

In [9]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [10]:
points.shape

torch.Size([3, 2])

In [11]:
points[0,1]

tensor(1.)

In [12]:
points[0]

tensor([4., 1.])

In [13]:
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [14]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [16]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)
double_points.dtype, short_points.dtype

(torch.float64, torch.int16)

In [17]:
points.storage()

C:\Users\abc\AppData\Local\Temp\ipykernel_9228\2396954748.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [18]:
points.untyped_storage()

 0
 0
 128
 64
 0
 0
 128
 63
 0
 0
 160
 64
 0
 0
 64
 64
 0
 0
 0
 64
 0
 0
 128
 63
[torch.storage.UntypedStorage(device=cpu) of size 24]

In [19]:
points.shape

torch.Size([3, 2])

In [20]:
points.is_contiguous()

True

In [21]:
points.stride()

(2, 1)

In [22]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [23]:
torch.save(points, 'outpoints.t')

In [24]:
with open('outpoints.t', 'rb') as f:
    points_loaded = torch.load(f)
points_loaded

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [25]:
import h5py
file = h5py.File('outpoints.hdf5','w')
dataset = file.create_dataset('coords', data=points.numpy())
file.close()

In [26]:
points_from_hdf5 = h5py.File('outpoints.hdf5','r')
dataset = points_from_hdf5['coords']
last_points = dataset[-2:]
last_points

array([[5., 3.],
       [2., 1.]], dtype=float32)

In [27]:
last_points = torch.from_numpy(dataset[-2:])
points_from_hdf5.close()
last_points

tensor([[5., 3.],
        [2., 1.]])

In [28]:
dataset

<Closed HDF5 dataset>

1．从list(range(9))创建一个张量a，预测并检查其大小、偏移量和步长。

a）使用b = a.view(3,3)创建一个张量，简述view()方法的功能，检查a和b是否共享同一个存储。

b）使用c = b[1:,1:]创建一个张量，预测并检查其大小、偏移量和步长。

In [29]:
a = torch.tensor(list(range(9)))
a.shape, a.storage().data_ptr(), a.stride()

(torch.Size([9]), 5380570939392, (1,))

In [30]:
b = a.view(3,3)
b.shape, b.storage().data_ptr(), b.stride()

(torch.Size([3, 3]), 5380570939392, (3, 1))

2．选择一个数据运算（如求余弦或平方根），你能在torch库中找到相应的函数吗？

a）按元素将函数作用于张量a，它为什么返回一个错误？

b）需要使用什么操作才能使函数正常工作？

c）你的函数有合适的版本吗？

In [31]:
torch.sin(a)

tensor([ 0.0000,  0.8415,  0.9093,  0.1411, -0.7568, -0.9589, -0.2794,  0.6570,
         0.9894])

In [32]:
a.sin()

tensor([ 0.0000,  0.8415,  0.9093,  0.1411, -0.7568, -0.9589, -0.2794,  0.6570,
         0.9894])

In [35]:
points_gpu = points.cuda()
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [36]:
points_gpu.cpu()

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])