In [1]:
import torch
_ = torch.tensor([0.2126,0.7152,0.0722],names=['c'])

/var/folders/pm/r8fcp13s1gqgh20ly21fl73c0000gn/T/ipykernel_673/3851847414.py:2: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/c10/core/TensorImpl.h:1903.)
  _ = torch.tensor([0.2126,0.7152,0.0722],names=['c'])


In [2]:
image_t = torch.randn(3, 5, 5)
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [3]:
image_t, weights

(tensor([[[-1.1272e+00, -1.3753e+00, -2.6807e-01,  1.2215e+00,  1.7771e+00],
          [-9.3588e-01,  1.8332e+00, -1.2846e-02, -1.0666e+00,  8.5603e-02],
          [-1.4984e+00,  1.1661e-02,  2.2387e-01, -1.7384e+00,  1.3493e-01],
          [-7.5744e-01, -2.2568e+00,  9.5576e-01,  9.3379e-01,  1.1772e-01],
          [ 3.7500e-01,  2.1418e-01, -4.6588e-01,  6.6081e-01, -7.6724e-02]],
 
         [[-6.9707e-01, -1.8235e+00,  1.5044e-01,  1.7496e+00,  1.9529e+00],
          [-8.0582e-01, -1.5654e+00, -7.9424e-02,  8.6918e-01, -2.1225e-03],
          [-1.4000e+00,  4.1336e-01,  1.2106e-01,  1.8831e+00,  5.3953e-02],
          [-7.0884e-01, -2.0445e-01, -7.7414e-01, -4.8586e-01,  4.8557e-01],
          [ 1.3950e+00, -1.7218e+00,  5.3339e-01,  5.4800e-01, -9.5955e-01]],
 
         [[ 5.2953e-01,  7.8256e-01,  4.0723e-01, -5.6411e-01,  5.7865e-01],
          [ 1.5167e+00, -1.3103e+00,  5.6275e-01, -1.2217e-01,  2.0087e+00],
          [-2.4280e-01, -1.7443e+00, -1.4551e+00,  7.1391e-01, -5.2855

In [4]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]
image_gray_naive = image_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
image_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [5]:
image_gray_naive

tensor([[-0.4316, -0.8054,  0.0965,  0.8023,  1.4362],
        [-0.0750, -0.3475,  0.1568, -0.1065,  0.6974],
        [-1.0471, -0.4398, -0.3701,  0.2862, -0.1132],
        [ 0.0698, -0.7975, -0.0356,  0.3738,  0.0869],
        [ 0.7078, -0.9911, -0.3496,  0.3648, -0.5422]])

In [11]:
image_small = torch.tensor([[[1.,2.],[3.,4.]], 
                            [[6.,6.],[7.,8.]], 
                            [[9.,10.],[11.,12.]]])
image_small.shape

torch.Size([3, 2, 2])

In [12]:
image_small_gray_naive = image_small.mean(-3)
image_small_gray_naive

tensor([[5.3333, 6.0000],
        [7.0000, 8.0000]])

In [15]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [16]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))