In [7]:
import numpy as np
# x - y = 0
# x + 2y = 8
# [ 1  -1 ][x]   [0]
# [ 1   2 ][y]   [8]
matrix = np.array(((1, -1), (1, 2)))
output = np.array((0,8))
xy = np.linalg.solve(matrix, output)
print(matrix)
print(output)
print(xy)

[[ 1 -1]
 [ 1  2]]
[0 8]
[2.66666667 2.66666667]


x + y - z = -1
2y - z = 3
x + z = 2

In [10]:
matrix = np.array(((1, 1, -1), (0, 2, -1), (1, 0, 1)))
vector = np.array((-1, 3, 2))
np.linalg.solve(matrix, vector)

array([-1.,  3.,  3.])

练习7.26，利用逆矩阵求方程的解

In [13]:
matrix = np.array(((1, 1, -1), (0, 2, -1), (1, 0, 1)))
vector = np.array((-1, 3, 2))
inverse = np.linalg.inv(matrix)
np.matmul(inverse,matrix)

array([[ 1.00000000e+00,  1.11022302e-16, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [14]:
np.matmul(vector, inverse)

array([-3.,  3.,  2.])

练习7.19

In [1]:
from vectors import *

def plane_equation(p1, p2, p3):
    p1p2 = subtract(p2, p1)
    p1p3 = subtract(p3, p1)
    a, b, c = cross(p1p2, p1p3)
    d = dot((a,b,c), p1)
    return a,b,c,d

In [2]:
plane_equation((1,1,1), (3,0,0), (0,3,0))

(3, 3, 3, 9)